# ALLINProcessor 1.0.0
# Переработка блоков руды через кафедру (LECTERN).

processing:
  seconds: 5
  cancel-if-too-far: true
  max-distance: 4.0

levels:
  # Уровень 1 -> 2: после 2000 успешных переработок счётчик сбрасывается.
  level-2-required: 2000

  # Уровень 2 -> 3: после 6000 успешных переработок счётчик сбрасывается.
  level-3-required: 6000

  # 3 уровень максимальный. Счётчик дальше идёт бесконечно.
  level-3-diamond-chance: 0.01

# Что получается из одного блока руды.
# Можно менять без пересборки JAR.
recipes:
  COAL_ORE: COAL
  DEEPSLATE_COAL_ORE: COAL

  COPPER_ORE: RAW_COPPER
  DEEPSLATE_COPPER_ORE: RAW_COPPER

  IRON_ORE: RAW_IRON
  DEEPSLATE_IRON_ORE: RAW_IRON

  GOLD_ORE: RAW_GOLD
  DEEPSLATE_GOLD_ORE: RAW_GOLD
  NETHER_GOLD_ORE: GOLD_NUGGET

  REDSTONE_ORE: REDSTONE
  DEEPSLATE_REDSTONE_ORE: REDSTONE

  LAPIS_ORE: LAPIS_LAZULI
  DEEPSLATE_LAPIS_ORE: LAPIS_LAZULI

  EMERALD_ORE: EMERALD
  DEEPSLATE_EMERALD_ORE: EMERALD

  DIAMOND_ORE: DIAMOND
  DEEPSLATE_DIAMOND_ORE: DIAMOND

  ANCIENT_DEBRIS: NETHERITE_SCRAP
