name: ALLINMiner
version: 1.1.2
main: com.allin.miner.AllinMiner
api-version: '26.2'
author: ALLIN
description: Special mining points and Miner skill for ALLIN
commands:
  miner:
    description: ALLIN Miner administration
    usage: /miner
    permission: allinminer.admin
permissions:
  allinminer.admin:
    default: op
